name: Podman CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | podman login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Podman image
        run: |
          podman build -t docker.io/${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }} .
          podman push docker.io/${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y podman
            podman login docker.io -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            podman pull docker.io/${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
            podman stop webapp || true
            podman rm webapp || true
            podman run -d --name webapp -p 8080:80 docker.io/${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
